include:
  - ./ide/docker-compose.yml
  - ./cli/docker-compose.yml
  - ./claude/docker-compose.yml
  - ./browser/docker-compose.yml
  - ./web/docker-compose.yml
  - ./webgrind/docker-compose.yml
networks:
  project:
    external: false