services:
  cli:
    hostname: 'cli'
    build:
      context: ./
      dockerfile: ./Dockerfile
      additional_contexts:
        common: "../common/"
    restart: "no"
    ports:
      - 50010:22
    volumes:
      - project:/opt/project:rw
      - logs:/opt/log:rw
      - ssh:/opt/ssh/:rw
      - xdebug:/opt/xdebug:rw
      - ../shared-folder:/opt/shared-folder:rw
    networks:
      - project
volumes:
  project:
    external: false
  xdebug:
    external: false
  ssh:
    external: false
  logs:
    external: false
networks:
  project:
    external: false